### ISSUE TITLE
Obsolete example, does not build with current Visual Studio 2019. Needs upgrade to .Net Core 3.1

### ISSUE THREAD

**Issue by bbmmcodegirl** [shahedc/AspNetCoreMiddlewareSample#1]
Uses obsolete .Net Core 2.2, needs code and package changes to build and run with .Net Core 3.1. Visual Studio 2019 won't build and run it as-is.

**Comment by shahedc** [comment]
Thanks for the note. This repo is an old sample for my Middleware blog post in my 2019 A-Z series. 

 * old Middleware post: https://wakeupandcode.com/middleware-in-asp-net-core/ 

I have a newer blog post to cover 3.1 in my 2020 A-Z series: 

* Middleware in 3.1: https://wakeupandcode.com/middleware-in-asp-net-core-3-1/

The 2020 series uses a single repo (NetLearner) for all samples, instead of separate unrelated samples as the 2019 series. The newer post mentioned above has a link to the NetLearner repo and explains how Middleware works. 

* NetLearner repo: https://github.com/shahedc/NetLearnerApp
